"""SYNTHETIC labeled dataset generator for the triage classifier (dev / eval only).

⚠️  EVERY row produced here is SYNTHETIC — it is NOT real analyst-labelled data and must
never be presented as such. Each generated record is stamped `synthetic=True`, and the
dataset carries a `SYNTHETIC_MARKER` header. This exists so the classifier and its eval
harness have a labelled corpus with a *known* signal before real `TriageLabel` data
accumulates; it is explicitly not a substitute for it.

Generative model (documented so the eval is interpretable): features are drawn from
plausible marginal distributions, then the actionable label is sampled from a logistic
model over a hand-set weight vector — high security-severity, injection-family CWE,
present dataflow trace, and a high per-rule prior mean push P(actionable) up; vendor/
generated/test paths, high historical FP rate, and high finding density push it down.
Class balance is set to a realistic ~30% actionable base rate (matching the sourced
Beta prior mean), so the harness measures precision-recall/Brier on an imbalanced,
learnable problem rather than a trivially separable one.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np

from .features import FEATURE_NAMES

SYNTHETIC_MARKER = "SYNTHETIC — generated by triage/synthetic.py; not real analyst labels"

# Logistic weights over FEATURE_NAMES. Signs encode the documented direction of each
# signal; magnitudes are illustrative (this is a synthetic teacher, not a fitted model).
_WEIGHTS: dict[str, float] = {
    "severity_ordinal": 0.45,
    "security_severity": 0.30,
    "cwe_is_injection": 1.30,
    "cwe_is_crypto": 0.35,
    "cwe_is_authz": 0.60,
    "cwe_known": 0.20,
    "rule_prior_mean": 1.60,
    "historical_fp_rate": -1.80,
    "rule_label_count_log": 0.05,
    "path_depth": -0.05,
    "is_test_path": -1.10,
    "is_vendor_dependency": -1.40,
    "is_generated": -1.20,
    "is_config_file": -0.30,
    "file_commit_count_log": 0.10,
    "file_recent_churn_log": 0.25,
    "file_age_days_log": -0.05,
    "dataflow_length": 0.12,
    "has_dataflow": 0.90,
    "finding_density_log": -0.55,
    "message_length_log": 0.05,
}
# Intercept tuned so the marginal actionable rate lands near the ~0.30 base rate.
_INTERCEPT = -1.15


@dataclass
class SyntheticDataset:
    """A synthetic feature matrix + labels, tagged so it can never pass as real data."""

    X: np.ndarray                       # shape (n, len(FEATURE_NAMES))
    y: np.ndarray                       # shape (n,), 0/1 actionable
    feature_names: list[str] = field(default_factory=lambda: list(FEATURE_NAMES))
    synthetic: bool = True              # invariant: always True
    marker: str = SYNTHETIC_MARKER

    def __post_init__(self) -> None:
        assert self.synthetic is True, "SyntheticDataset must be flagged synthetic"


def _sample_features(rng: np.random.Generator, n: int) -> dict[str, np.ndarray]:
    """Draw each feature from a plausible marginal distribution."""
    prior_mean = rng.beta(3, 7, n)                       # matches the sourced prior
    return {
        "severity_ordinal": rng.integers(0, 4, n).astype(float),
        "security_severity": np.clip(rng.normal(5, 2.5, n), 0, 10),
        "cwe_is_injection": (rng.random(n) < 0.25).astype(float),
        "cwe_is_crypto": (rng.random(n) < 0.12).astype(float),
        "cwe_is_authz": (rng.random(n) < 0.10).astype(float),
        "cwe_known": (rng.random(n) < 0.80).astype(float),
        "rule_prior_mean": prior_mean,
        "historical_fp_rate": np.clip(rng.beta(2, 3, n), 0, 1),
        "rule_label_count_log": np.log1p(rng.poisson(6, n)),
        "path_depth": rng.integers(1, 9, n).astype(float),
        "is_test_path": (rng.random(n) < 0.18).astype(float),
        "is_vendor_dependency": (rng.random(n) < 0.15).astype(float),
        "is_generated": (rng.random(n) < 0.08).astype(float),
        "is_config_file": (rng.random(n) < 0.10).astype(float),
        "file_commit_count_log": np.log1p(rng.poisson(12, n)),
        "file_recent_churn_log": np.log1p(rng.poisson(3, n)),
        "file_age_days_log": np.log1p(rng.integers(1, 1500, n)),
        "dataflow_length": rng.poisson(2, n).astype(float),
        "has_dataflow": np.zeros(n),                     # set below from dataflow_length
        "finding_density_log": np.log1p(rng.poisson(4, n)),
        "message_length_log": np.log1p(rng.integers(20, 200, n)),
    }


def generate(n: int = 2000, seed: int = 1337, label_noise: float = 0.05) -> SyntheticDataset:
    """Generate `n` SYNTHETIC labelled findings over the `FEATURE_NAMES` schema.

    `label_noise` flips a fraction of labels so the problem is not perfectly separable
    (a realistic Brier score depends on irreducible noise). Deterministic given `seed`.
    """
    rng = np.random.default_rng(seed)
    cols = _sample_features(rng, n)
    cols["has_dataflow"] = (cols["dataflow_length"] > 0).astype(float)

    X = np.column_stack([cols[name] for name in FEATURE_NAMES])

    logits = np.full(n, _INTERCEPT)
    for i, name in enumerate(FEATURE_NAMES):
        logits += _WEIGHTS[name] * X[:, i]
    p = 1.0 / (1.0 + np.exp(-logits))
    y = (rng.random(n) < p).astype(int)

    if label_noise > 0:
        flip = rng.random(n) < label_noise
        y[flip] = 1 - y[flip]

    return SyntheticDataset(X=X, y=y)
